import { ReadingPreset } from '../storage/storage';

/**
 * 内置预设列表
 */
export const builtInPresets: ReadingPreset[] = [
  {
    id: 'dark-comfort',
    name: '暗色舒适',
    description: '深色背景配合舒适字体，减少眼睡',
    isBuiltIn: true,
    settings: {
      theme: 'dark',
      fontSize: 19,
      codeFontSize: 15,
      codeTheme: 'dracula',
      lineHeight: 1.8,
      lineSpacing: 2.0,
      letterSpacing: 0.4,
      pageWidth: 700,
      textAlign: 'left',
      firstLineIndent: true,
      showImages: true,
      showDirectory: false, // 默认不显示目录
      fontFamily: 'songti',
      backgroundColor: 'cool',
      paragraphSpacing: 1.5,
    }
  },
  {
    id: 'default',
    name: '默认',
    description: '默认阅读设置',
    isBuiltIn: true,
    settings: {
      theme: 'light',
      fontSize: 18,
      codeFontSize: 14,
      codeTheme: 'github',
      lineHeight: 1.6,
      lineSpacing: 1.8,
      letterSpacing: 0.1,
      pageWidth: 800,
      textAlign: 'left',
      firstLineIndent: true,
      showImages: true,
      showDirectory: false, // 默认不显示目录
      fontFamily: 'default',
      backgroundColor: 'white',
      paragraphSpacing: 1.2,
    }
  },
  {
    id: 'comfortable',
    name: '舒适阅读',
    description: '更大的字体和更宽松的间距，适合长时间阅读',
    isBuiltIn: true,
    settings: {
      theme: 'light',
      fontSize: 20,
      lineHeight: 1.8,
      lineSpacing: 2.0,
      letterSpacing: 0.5,
      pageWidth: 700,
      textAlign: 'left',
      firstLineIndent: true,
      fontFamily: 'songti',
      backgroundColor: 'cream',
      paragraphSpacing: 1.5,
    }
  },
  {
    id: 'compact',
    name: '紧凑模式',
    description: '更小的字体和更紧凑的间距，适合信息密集型内容',
    isBuiltIn: true,
    settings: {
      theme: 'light',
      fontSize: 16,
      lineHeight: 1.3,
      lineSpacing: 1.4,
      letterSpacing: 0,
      pageWidth: 900,
      textAlign: 'justify',
      firstLineIndent: false,
      fontFamily: 'heiti',
      backgroundColor: 'white',
      paragraphSpacing: 0.8,
    }
  },
  {
    id: 'night',
    name: '夜间模式',
    description: '深色背景，适合夜间阅读',
    isBuiltIn: true,
    settings: {
      theme: 'dark',
      fontSize: 18,
      codeFontSize: 14,
      codeTheme: 'one-dark',
      lineHeight: 1.7,
      lineSpacing: 1.9,
      letterSpacing: 0.3,
      pageWidth: 720,
      textAlign: 'left',
      firstLineIndent: true,
      fontFamily: 'default',
      backgroundColor: 'cool', // 在暗色主题中背景色由主题控制
      paragraphSpacing: 1.4,
      showImages: true,
      showDirectory: false, // 默认不显示目录
    }
  },
  {
    id: 'focus',
    name: '专注模式',
    description: '简洁的布局，无图片，适合需要专注的阅读',
    isBuiltIn: true,
    settings: {
      theme: 'light',
      fontSize: 19,
      codeFontSize: 15,
      codeTheme: 'github',
      lineHeight: 1.7,
      lineSpacing: 1.9,
      letterSpacing: 0.3,
      pageWidth: 650,
      textAlign: 'left',
      firstLineIndent: true,
      showImages: false,
      showDirectory: false,
      fontFamily: 'default',
      backgroundColor: 'gray',
      paragraphSpacing: 1.3,
    }
  },
  {
    id: 'academic',
    name: '学术阅读',
    description: '适合学术论文和技术文档的阅读',
    isBuiltIn: true,
    settings: {
      theme: 'light',
      fontSize: 17,
      codeFontSize: 15,
      codeTheme: 'github',
      lineHeight: 1.6,
      lineSpacing: 1.8,
      letterSpacing: 0.1,
      pageWidth: 850,
      textAlign: 'justify',
      firstLineIndent: false,
      showImages: true,
      showDirectory: true,
      fontFamily: 'default',
      backgroundColor: 'cool',
      paragraphSpacing: 1.2,
    }
  },
  {
    id: 'novel',
    name: '小说模式',
    description: '适合小说和长篇文学作品的阅读',
    isBuiltIn: true,
    settings: {
      theme: 'light',
      fontSize: 19,
      lineHeight: 1.8,
      lineSpacing: 2.0,
      letterSpacing: 0.2,
      pageWidth: 700,
      textAlign: 'justify',
      firstLineIndent: true,
      showImages: true,
      showDirectory: true,
      fontFamily: 'songti',
      backgroundColor: 'sepia',
      paragraphSpacing: 1.5,
    }
  },
];
